# Generated by Django 4.2.7 on 2024-02-20 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0012_alter_attendance_day'),
        ('users', '0002_rename_department_district_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True)),
                ('description', models.IntegerField(blank=True)),
                ('type', models.IntegerField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Credit')),
                ('date', models.DateField(default=datetime.datetime(2024, 2, 20, 8, 23, 55, 740119, tzinfo=datetime.timezone.utc))),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.district')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='secretary_t_date_a550f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.district')),
            ],
            options={
                'ordering': ['district'],
                'indexes': [models.Index(fields=['district'], name='secretary_i_distric_411462_idx')],
            },
        ),
        migrations.CreateModel(
            name='Church_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200, null=True)),
                ('country', models.CharField(blank=True, default='Nigeria', max_length=200, null=True)),
                ('LGA', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.district')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='secretary_c_date_328c59_idx')],
            },
        ),
        migrations.CreateModel(
            name='Church_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_boy', models.IntegerField(blank=True)),
                ('children_girl', models.IntegerField(blank=True)),
                ('men', models.IntegerField(blank=True)),
                ('women', models.IntegerField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.district')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='secretary_c_date_3db99a_idx')],
            },
        ),
    ]
