# Generated by Django 4.2.7 on 2024-02-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_member_department_alter_member_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
