# Generated by Django 4.2.7 on 2024-02-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['date']},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['-name'], name='administrat_name_07f49e_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['date'], name='administrat_date_17349a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['date'], name='administrat_date_5b6668_idx'),
        ),
    ]
