# Generated by Django 4.2.7 on 2024-02-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='administrat_date_5b6668_idx',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-date'], name='administrat_date_d779fb_idx'),
        ),
    ]
