# Generated by Django 4.2.7 on 2024-02-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.CharField(blank=True, choices=[('Day 1', 'Day 1'), ('Day 2', 'Day 2'), ('Day 3', 'Day 3')], max_length=200, null=True),
        ),
    ]
