# Generated by Django 4.2.7 on 2024-02-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_attendance_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
